"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
"""


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        letters={}
        for c in s:
            letters[c]= letters[c]+1 if c in letters else 1
        for c in t:
            if c not in letters:
                return c
            else:
                letters[c]-=1
            if letters[c]<0:
                return c

"""
算法思路：利用dict s的字母存入dict并且计数，然后遍历t的字母，出现一次相同的字母，value-1，value为负数即difference，没出现的字母就肯定是difference
或者对于s的每个字母在t中找返回的是下标，删掉找到的。留下的就是difference
"""